image: alpine/edge
packages:
  - dotnet8-sdk
  - just
tasks:
  - build: |
      cd skvis
      just build-all
artifacts:
  - 'skvis/Skvis/bin/Release/net8.0/osx-x64/publish/Skvis.app'
  - 'skvis/Skvis/bin/Release/net8.0/win-x64/publish/Skvis.exe'
  - 'skvis/Skvis/bin/Release/net8.0/linux-x64/publish/Skvis'
