image: alpine/edge
packages:
  - dotnet8-sdk
  - just
  - zip
tasks:
  - build: |
      cd skvis
      just build-zip-all
artifacts:
  - 'skvis/Skvis/bin/Release/net8.0/osx-x64/publish/Skvis-macos.zip'
  - 'skvis/Skvis/bin/Release/net8.0/win-x64/publish/Skvis-win.zip'
  - 'skvis/Skvis/bin/Release/net8.0/linux-x64/publish/Skvis-linux.zip'
